<template>
  <div class="p-8">
    <div class="bg-primary-900 p-2">
      <img src="@/assets/icons/logo/LTELogo.png" class="h-10" />
    </div>
    <div class="font-bold text-[40px] mt-4">Terms & Conditions</div>
    <div class="text-[16px] ml-8">Updated at 2022-07-12</div>
    <br />

    <div class="font-bold text-[40px]">General Terms</div>
    <div class="text-[16px] ml-8">
      <div>
        By accessing and placing an order with , you confirm that you are in
        agreement with and bound by the terms of service contained in the Terms
        & Conditions outlined below. These terms apply to the entire website and
        any email or other type of communication.
      </div>
      <br />
      <div>
        Under no circumstances shall team be liable for any direct, indirect,
        special, incidental or consequential damages, including, but not limited
        to, loss of data or profit, arising out of the use, or the inability to
        use, the materials on this site, even if team or an authorized
        representative has been advised of the possibility of such damages. If
        your use of materials from this site results in the need for servicing,
        repair or correction of equipment or data, you assume any costs thereof.
      </div>
      <br />
      <div>
        will not be responsible for any outcome that may occur during the course
        of usage of our resources. We reserve the rights to change prices and
        revise the resources usage policy in any moment.
      </div>
    </div>
    <br />

    <div class="font-bold text-[40px]">License</div>
    <div class="text-[16px] ml-8">
      <div>
        LearnToEarn grants you a revocable, non-exclusive, non- transferable,
        limited license to download, install and use our service strictly in
        accordance with the terms of this Agreement.
      </div>
      <br />
      <div>
        These Terms & Conditions are a contract between you and LearnToEarn
        (referred to in these Terms & ", "we" or "our"), the provider of the
        LearnToEarn website and the services accessible from the LearnToEarn
        website (which are collectively referred to in these Terms & Conditions
        as the "LearnToEarn Service").
      </div>
      <br />
      <div>
        You are agreeing to be bound by these Terms & Conditions. If you do not
        agree to these Terms & Conditions, please do not use the Service. In
        these Terms & Conditions, "you" refers both to you as an individual and
        to the entity you represent. If you violate any of these Terms &
        Conditions, we reserve the right to cancel your account or block access
        to your account without notice.
      </div>
    </div>
    <br />

    <div class="font-bold text-[40px]">Definitions and key terms</div>
    <div class="text-[16px] ml-8">
      <div>For this Terms & Conditions:</div>
      <br />
      <div>
        <b>Cookie:</b> small amount of data generated by a website and saved by
        your web browser. It is used to identify your browser, provide
        analytics, remember information about you such as your language
        preference or login information.
      </div>
      <br />
      <div>
        <b>Company:</b> when this policy mentions “Company,” “we,” “ responsible
        for your information under this Privacy Policy.
      </div>
      <br />
      <div>
        <b>Country:</b> where LearnToEarn or the owners/founders of LearnToEarn
        are based, in this case is Thailand.
      </div>
      <br />
      <div>
        <b>Customer:</b> refers to the company, organization or person that
        signs up to use the LearnToEarn Service to manage the relationships with
        your consumers or service users.
      </div>
      <br />
      <div>
        <b>Device:</b> any internet connected device such as a phone, tablet,
        computer or any other device that can be used to visit LearnToEar and
        use the services.
      </div>
      <br />
      <div>
        <b>IP address:</b> Every device connected to the Internet is assigned a
        number known as an Internet protocol (IP) address. These numbers are
        usually assigned in geographic blocks. An IP address can often be used
        to identify the location from which a device is connecting to the
        Internet.
      </div>
      <br />
      <div>
        <b>Personnel:</b> refers to those individuals who are employed by
        LearnToEar or are under contract to perform a service on behalf of one
        of the parties.
      </div>
      <br />
      <div>
        <b>Personal Data:</b> any information that directly, indirectly, or in
        connection with other information — including a personal identification
        number — allows for the identification or identifiability of a natural
        person.
      </div>
      <br />
      <div>
        <b>Service:</b> refers to the service provided by LearnToEarn as
        described in the relative terms (if available) and on this platform.
      </div>
      <br />
      <div>
        <b>Third-party service:</b> refers to advertisers, contest sponsors,
        promotional and marketing partners, and others who provide our content
        or whose products or services we think may interest you.
      </div>
      <br />
      <div>
        <b>You:</b> a person or entity that is registered with LearnToEarn to
        use the Services.
      </div>
    </div>
    <br />

    <div class="font-bold text-[40px]">Restrictions</div>
    <div class="text-[16px] ml-8">
      <div>You agree not to, and you will not permit others to:</div>
      <br />
      <div>
        License, sell, rent, lease, assign, distribute, transmit, host,
        outsource, disclose or otherwise commercially exploit the service or
        make the platform available to any third party.
      </div>
      <br />
      <div>
        Modify, make derivative works of, disassemble, decrypt, reverse compile
        or reverse engineer any part of the service.
      </div>
      <br />
      <div>
        Remove, alter or obscure any proprietary notice (including any notice of
        copyright or trademark) of or its affiliates, partners, suppliers or the
        licensors of the service.
      </div>
    </div>
    <br />

    <div class="font-bold text-[40px]">Miscellaneous</div>
    <div class="text-[16px] ml-8">
      If for any reason a court of competent jurisdiction finds any provision or
      portion of these Terms & Conditions to be unenforceable, the remainder of
      these Terms & Conditions will continue in full force and effect. Any
      waiver of any provision of these Terms & Conditions will be effective only
      if in writing and signed by an authorized representative of us. We will be
      entitled to injunctive or other equitable relief (without the obligations
      of posting any bond or surety) in the event of any breach or anticipatory
      breach by you. We operate and control our Service from our offices in .
      The Service is not intended for distribution to or use by any person or
      entity in any jurisdiction or country where such distribution or use would
      be contrary to law or regulation. Accordingly, those persons who choose to
      access our Service from other locations do so on their own initiative and
      are solely responsible for compliance with local laws, if and to the
      extent local laws are applicable. These Terms & Conditions (which include
      and incorporate our Privacy Policy) contains the entire understanding, and
      supersedes all prior understandings, between you and us concerning its
      subject matter, and cannot be changed or modified by you. The section
      headings used in this Agreement are for convenience only and will not be
      given any legal import.
    </div>
    <br />

    <div class="font-bold text-[40px]">Disclaimer</div>
    <div class="text-[16px] ml-8">
      <div>
        We are not responsible for any content, code or any other imprecision.
        We do not provide warranties or guarantees. In no event shall we be
        liable for any special, direct, indirect, consequential, or incidental
        damages or any damages whatsoever, whether in an action of contract,
        negligence or other tort, arising out of or in connection with the use
        of the Service or the contents of the Service. We reserve the right to
        make additions, deletions, or modifications to the contents on the
        Service at any time without prior notice.
      </div>
      <br />
      <div>
        Our Service and its contents are provided "as is" and “as available"
        without any warranty or representations of any kind, whether express or
        implied. We are a distributor and not a publisher of the content
        supplied by third parties; as such, our exercises no editorial control
        over such content and makes no warranty or representation as to the
        accuracy, reliability or currency of any information, content, service
        or merchandise provided through or accessible via our Service. Without
        limiting the foregoing, We specifically disclaim all warranties and
        representations in any content transmitted on or in connection with our
        Service or on sites that may appear as links on our Service, or in the
        products provided as a part of, or otherwise in connection with, our
        Service, including without limitation any warranties of merchantability,
        fitness for a particular purpose or non-infringement of third party
        rights. No oral advice or written information given by us or any of its
        affiliates, employees, officers, directors, agents, or the like will
        create a warranty. Price and availability information is subject to
        change without notice. Without limiting the foregoing, we do not warrant
        that our Service will be uninterrupted, uncorrupted, timely, or
        error-free.
      </div>
    </div>
    <br />

    <div class="font-bold text-[40px]">Disclaimer</div>
    <div class="text-[16px] ml-8">
      <div>Don't hesitate to contact us if you have any questions.</div>
      <br />
      <div>- Via Email: Decha_L@cmu.ac.th</div>
    </div>
    <br />
  </div>
</template>
